export const THEMES = {
  blossom: {
    id: 'blossom',
    name: 'Blossom',
    description: 'Blush pink with gold accents',
    preview: {
      primary: '#D4829A',
      accent: '#C9A84C',
      bg: '#FFFDF7',
    },
    vars: {
      '--color-primary': '#D4829A',
      '--color-primary-light': '#F2C4D0',
      '--color-accent': '#C9A84C',
      '--color-accent-light': '#F0E0A8',
      '--color-bg': '#FFFDF7',
      '--color-surface': '#FFF5F7',
      '--color-border': '#F0D8DF',
      '--color-text': '#4A2C35',
      '--color-text-muted': '#9A7A82',
      '--color-success': '#7BAE7F',
      '--color-warning': '#E8A44A',
      '--color-danger': '#C0505A',
      '--color-card-bg': '#FFFFFF',
      '--color-navbar-bg': '#FFFDF7',
      '--color-button-text': '#FFFFFF',
      '--color-heading': '#b5687a',
    },
  },
  sapphire: {
    id: 'sapphire',
    name: 'Sapphire',
    description: 'Deep navy with champagne gold',
    preview: {
      primary: '#1B2B5E',
      accent: '#C9A84C',
      bg: '#FFFFFF',
    },
    vars: {
      '--color-primary': '#1B2B5E',
      '--color-primary-light': '#2E4A8C',
      '--color-accent': '#C9A84C',
      '--color-accent-light': '#F0E0A8',
      '--color-bg': '#F8F9FC',
      '--color-surface': '#EEF1F8',
      '--color-border': '#CBD5E1',
      '--color-text': '#1B2B5E',
      '--color-text-muted': '#64748B',
      '--color-success': '#2D6A4F',
      '--color-warning': '#B57C2B',
      '--color-danger': '#9E2121',
      '--color-card-bg': '#FFFFFF',
      '--color-navbar-bg': '#1B2B5E',
      '--color-button-text': '#FFFFFF',
      '--color-heading': '#1a2f5e',
    },
  },
  garden: {
    id: 'garden',
    name: 'Garden',
    description: 'Sage green with warm beige',
    preview: {
      primary: '#6B9E78',
      accent: '#C8B89A',
      bg: '#F8F6F0',
    },
    vars: {
      '--color-primary': '#6B9E78',
      '--color-primary-light': '#A8C9B0',
      '--color-accent': '#C8B89A',
      '--color-accent-light': '#EDE3D3',
      '--color-bg': '#F8F6F0',
      '--color-surface': '#EFF0E8',
      '--color-border': '#D8CEBC',
      '--color-text': '#3D4B3F',
      '--color-text-muted': '#7A8C7D',
      '--color-success': '#4A7C59',
      '--color-warning': '#A87C3A',
      '--color-danger': '#A0403A',
      '--color-card-bg': '#FDFCF8',
      '--color-navbar-bg': '#4A6E52',
      '--color-button-text': '#FFFFFF',
      '--color-heading': '#3d6b4f',
    },
  },
  noir: {
    id: 'noir',
    name: 'Noir',
    description: 'Charcoal with rose gold accents',
    preview: {
      primary: '#2C2C2C',
      accent: '#B76E79',
      bg: '#FFFFFF',
    },
    vars: {
      '--color-primary': '#2C2C2C',
      '--color-primary-light': '#4A4A4A',
      '--color-accent': '#B76E79',
      '--color-accent-light': '#E8B4BB',
      '--color-bg': '#FAFAFA',
      '--color-surface': '#F0F0F0',
      '--color-border': '#DCDCDC',
      '--color-text': '#1A1A1A',
      '--color-text-muted': '#6B6B6B',
      '--color-success': '#3D7A4E',
      '--color-warning': '#A07030',
      '--color-danger': '#A02828',
      '--color-card-bg': '#FFFFFF',
      '--color-navbar-bg': '#1A1A1A',
      '--color-button-text': '#FFFFFF',
      '--color-heading': '#4a2030',
    },
  },
}

export const DEFAULT_THEME = 'blossom'
