// South African sample venue and supplier data

export const SAMPLE_VENUES = [
  {
    id: 'v1',
    name: 'Babylonstoren Wine Estate',
    location: 'Franschhoek, Western Cape',
    province: 'western-cape',
    capacity: 200,
    priceRange: 'R80,000 – R150,000',
    priceMin: 80000,
    priceMax: 150000,
    rating: 4.9,
    catering: true,
    accommodation: true,
    image: 'https://images.unsplash.com/photo-1510076857177-7470076d4098?auto=format&fit=crop&w=700&q=80',
    description: 'Stunning wine farm in the heart of Franschhoek with mountain views and lush gardens.',
    mapsQuery: 'Babylonstoren+Wine+Estate+Franschhoek',
    contact: '+27 21 863 3852',
  },
  {
    id: 'v2',
    name: 'Shepstone Gardens',
    location: 'Johannesburg, Gauteng',
    province: 'gauteng',
    capacity: 300,
    priceRange: 'R50,000 – R120,000',
    priceMin: 50000,
    priceMax: 120000,
    rating: 4.7,
    catering: true,
    accommodation: false,
    image: 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=700&q=80',
    description: 'A fairy-tale garden venue nestled in the suburb of Lyndhurst, Johannesburg.',
    mapsQuery: 'Shepstone+Gardens+Johannesburg',
    contact: '+27 11 616 5678',
  },
  {
    id: 'v3',
    name: 'Rhebokskloof Wine Estate',
    location: 'Paarl, Western Cape',
    province: 'western-cape',
    capacity: 180,
    priceRange: 'R60,000 – R110,000',
    priceMin: 60000,
    priceMax: 110000,
    rating: 4.8,
    catering: true,
    accommodation: true,
    image: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=700&q=80',
    description: 'An award-winning wine estate with breathtaking mountain backdrops and impeccable service.',
    mapsQuery: 'Rhebokskloof+Wine+Estate+Paarl',
    contact: '+27 21 869 8386',
  },
  {
    id: 'v4',
    name: 'Avianto Estate',
    location: 'Muldersdrift, Gauteng',
    province: 'gauteng',
    capacity: 400,
    priceRange: 'R45,000 – R100,000',
    priceMin: 45000,
    priceMax: 100000,
    rating: 4.6,
    catering: true,
    accommodation: true,
    image: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=700&q=80',
    description: 'A luxury estate nestled in the Cradle of Humankind with beautiful bush surroundings.',
    mapsQuery: 'Avianto+Estate+Muldersdrift',
    contact: '+27 11 957 2070',
  },
  {
    id: 'v5',
    name: 'Erinvale Estate Hotel',
    location: 'Somerset West, Western Cape',
    province: 'western-cape',
    capacity: 150,
    priceRange: 'R70,000 – R130,000',
    priceMin: 70000,
    priceMax: 130000,
    rating: 4.8,
    catering: true,
    accommodation: true,
    image: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=700&q=80',
    description: 'Set against the majestic Hottentots Holland Mountains with panoramic views.',
    mapsQuery: 'Erinvale+Estate+Hotel+Somerset+West',
    contact: '+27 21 847 1160',
  },
  {
    id: 'v6',
    name: 'Summerhill Guest Farm',
    location: 'Magaliesburg, North West',
    province: 'north-west',
    capacity: 120,
    priceRange: 'R30,000 – R65,000',
    priceMin: 30000,
    priceMax: 65000,
    rating: 4.5,
    catering: false,
    accommodation: true,
    image: 'https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?auto=format&fit=crop&w=700&q=80',
    description: 'A charming guest farm in the Magaliesberg mountains — ideal for intimate weddings.',
    mapsQuery: 'Summerhill+Guest+Farm+Magaliesburg',
    contact: '+27 14 577 1661',
  },
  {
    id: 'v7',
    name: 'Spier Wine Farm',
    location: 'Stellenbosch, Western Cape',
    province: 'western-cape',
    capacity: 500,
    priceRange: 'R90,000 – R200,000',
    priceMin: 90000,
    priceMax: 200000,
    rating: 4.9,
    catering: true,
    accommodation: true,
    image: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?auto=format&fit=crop&w=700&q=80',
    description: 'One of South Africa\'s oldest wine estates, offering multiple event spaces and luxurious accommodation.',
    mapsQuery: 'Spier+Wine+Farm+Stellenbosch',
    contact: '+27 21 809 1100',
  },
  {
    id: 'v8',
    name: 'Gateway Private Game Reserve',
    location: 'Bela-Bela, Limpopo',
    province: 'limpopo',
    capacity: 100,
    priceRange: 'R55,000 – R95,000',
    priceMin: 55000,
    priceMax: 95000,
    rating: 4.6,
    catering: true,
    accommodation: true,
    image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=700&q=80',
    description: 'A bush wedding experience in the heart of the Limpopo bushveld — safari style luxury.',
    mapsQuery: 'Gateway+Private+Game+Reserve+Bela-Bela',
    contact: '+27 14 736 8000',
  },
]

export const SAMPLE_SUPPLIERS = {
  photographers: [
    { id: 'p1', name: 'Yolande Marx Photography', location: 'Cape Town, Western Cape', priceRange: 'R18,000 – R35,000', rating: 4.9, mapsQuery: 'Cape+Town+Wedding+Photography', contact: '+27 71 234 5678', speciality: 'Fine art & documentary' },
    { id: 'p2', name: 'Liam Botma Studios', location: 'Johannesburg, Gauteng', priceRange: 'R15,000 – R28,000', rating: 4.7, mapsQuery: 'Liam+Botma+Studios+Johannesburg', contact: '+27 82 345 6789', speciality: 'Editorial & lifestyle' },
    { id: 'p3', name: 'Kobus Tollig Photography', location: 'Stellenbosch, Western Cape', priceRange: 'R20,000 – R40,000', rating: 4.9, mapsQuery: 'Kobus+Tollig+Photography+Stellenbosch', contact: '+27 72 456 7890', speciality: 'Wine estate specialist' },
  ],
  djs: [
    { id: 'd1', name: 'DJ Sliqe Events', location: 'Johannesburg, Gauteng', priceRange: 'R8,000 – R18,000', rating: 4.8, mapsQuery: 'DJ+Sliqe+Events+Johannesburg', contact: '+27 83 567 8901', speciality: 'Afro-house & Top 40' },
    { id: 'd2', name: 'Cape Sound Weddings', location: 'Cape Town, Western Cape', priceRange: 'R10,000 – R22,000', rating: 4.7, mapsQuery: 'Cape+Sound+Weddings+Cape+Town', contact: '+27 74 678 9012', speciality: 'Jazz, R&B & classics' },
    { id: 'd3', name: 'Vibe Masters SA', location: 'Durban, KwaZulu-Natal', priceRange: 'R7,000 – R15,000', rating: 4.6, mapsQuery: 'Vibe+Masters+SA+Durban', contact: '+27 65 789 0123', speciality: 'Indian Fusion & Top 40' },
  ],
  florists: [
    { id: 'f1', name: 'Blooms & Botanicals', location: 'Cape Town, Western Cape', priceRange: 'R15,000 – R40,000', rating: 4.9, mapsQuery: 'Blooms+Botanicals+Cape+Town', contact: '+27 71 890 1234', speciality: 'Garden & wildflower arrangements' },
    { id: 'f2', name: 'The Flower Studio JHB', location: 'Sandton, Gauteng', priceRange: 'R12,000 – R30,000', rating: 4.7, mapsQuery: 'The+Flower+Studio+Sandton', contact: '+27 82 901 2345', speciality: 'Luxury & bespoke florals' },
    { id: 'f3', name: 'Fynbos & Feathers', location: 'Stellenbosch, Western Cape', priceRange: 'R18,000 – R45,000', rating: 4.8, mapsQuery: 'Fynbos+Feathers+Stellenbosch', contact: '+27 73 012 3456', speciality: 'Fynbos & protea specialist' },
  ],
  caterers: [
    { id: 'c1', name: 'Cape Fusion Catering', location: 'Cape Town, Western Cape', priceRange: 'R350 – R650 per person', rating: 4.8, mapsQuery: 'Cape+Fusion+Catering+Cape+Town', contact: '+27 21 123 4567', speciality: 'Cape Malay & fusion cuisine' },
    { id: 'c2', name: 'Braai Kings Events', location: 'Johannesburg, Gauteng', priceRange: 'R250 – R450 per person', rating: 4.6, mapsQuery: 'Braai+Kings+Events+Johannesburg', contact: '+27 11 234 5678', speciality: 'Traditional South African braai' },
    { id: 'c3', name: 'Spice Route Catering', location: 'Durban, KwaZulu-Natal', priceRange: 'R300 – R550 per person', rating: 4.7, mapsQuery: 'Spice+Route+Catering+Durban', contact: '+27 31 345 6789', speciality: 'Indian & international cuisine' },
  ],
  makeup: [
    { id: 'm1', name: 'Glow by Lourens', location: 'Cape Town, Western Cape', priceRange: 'R3,500 – R8,000', rating: 4.9, mapsQuery: 'Glow+by+Lourens+Cape+Town', contact: '+27 71 456 7890', speciality: 'Bridal & editorial makeup' },
    { id: 'm2', name: 'Flawless Faces SA', location: 'Johannesburg, Gauteng', priceRange: 'R2,800 – R6,500', rating: 4.8, mapsQuery: 'Flawless+Faces+SA+Johannesburg', contact: '+27 82 567 8901', speciality: 'Airbrush & HD makeup' },
    { id: 'm3', name: 'Beauty & The Bridal', location: 'Pretoria, Gauteng', priceRange: 'R2,500 – R5,500', rating: 4.7, mapsQuery: 'Beauty+The+Bridal+Pretoria', contact: '+27 72 678 9012', speciality: 'Natural & glam looks' },
  ],
  cakes: [
    { id: 'wc1', name: 'Sugar & Lace Cakes', location: 'Cape Town, Western Cape', priceRange: 'R4,500 – R15,000', rating: 4.9, mapsQuery: 'Sugar+Lace+Cakes+Cape+Town', contact: '+27 71 789 0123', speciality: 'Fondant & floral wedding cakes' },
    { id: 'wc2', name: 'The Cake Studio Joburg', location: 'Johannesburg, Gauteng', priceRange: 'R3,500 – R12,000', rating: 4.8, mapsQuery: 'The+Cake+Studio+Joburg', contact: '+27 82 890 1234', speciality: 'Sculpted & tiered cakes' },
    { id: 'wc3', name: 'Cake Couture Durban', location: 'Durban, KwaZulu-Natal', priceRange: 'R3,000 – R10,000', rating: 4.7, mapsQuery: 'Cake+Couture+Durban', contact: '+27 31 901 2345', speciality: 'Dessert tables & drip cakes' },
  ],
  cars: [
    { id: 'cr1', name: 'Classic Car Hire SA', location: 'Cape Town, Western Cape', priceRange: 'R5,000 – R15,000', rating: 4.8, mapsQuery: 'Classic+Car+Hire+SA+Cape+Town', contact: '+27 21 456 7890', speciality: 'Vintage & luxury vehicles' },
    { id: 'cr2', name: 'Prestige Wedding Cars JHB', location: 'Johannesburg, Gauteng', priceRange: 'R4,500 – R12,000', rating: 4.7, mapsQuery: 'Prestige+Wedding+Cars+Johannesburg', contact: '+27 11 567 8901', speciality: 'Rolls Royce, Bentley & Mercedes' },
    { id: 'cr3', name: 'VIP Bridal Transport', location: 'Pretoria, Gauteng', priceRange: 'R3,500 – R9,000', rating: 4.6, mapsQuery: 'VIP+Bridal+Transport+Pretoria', contact: '+27 12 678 9012', speciality: 'Chauffeur-driven luxury cars' },
  ],
  decor: [
    { id: 'dc1', name: 'Enchanted Decor Hire', location: 'Cape Town, Western Cape', priceRange: 'R15,000 – R50,000', rating: 4.8, mapsQuery: 'Enchanted+Decor+Hire+Cape+Town', contact: '+27 71 234 5678', speciality: 'Bohemian & garden party décor' },
    { id: 'dc2', name: 'The Wedding Warehouse JHB', location: 'Johannesburg, Gauteng', priceRange: 'R10,000 – R40,000', rating: 4.7, mapsQuery: 'The+Wedding+Warehouse+Johannesburg', contact: '+27 82 345 6789', speciality: 'Marquee, furniture & lighting hire' },
    { id: 'dc3', name: 'Luxe Events Durban', location: 'Durban, KwaZulu-Natal', priceRange: 'R12,000 – R35,000', rating: 4.6, mapsQuery: 'Luxe+Events+Durban', contact: '+27 31 456 7890', speciality: 'Chic & modern event styling' },
  ],
}

export const PROVINCES = [
  { value: '', label: 'All Provinces' },
  { value: 'western-cape', label: 'Western Cape' },
  { value: 'gauteng', label: 'Gauteng' },
  { value: 'kwazulu-natal', label: 'KwaZulu-Natal' },
  { value: 'eastern-cape', label: 'Eastern Cape' },
  { value: 'limpopo', label: 'Limpopo' },
  { value: 'mpumalanga', label: 'Mpumalanga' },
  { value: 'north-west', label: 'North West' },
  { value: 'free-state', label: 'Free State' },
  { value: 'northern-cape', label: 'Northern Cape' },
]
